### ISSUE TITLE
Name change for solution java class file

### ISSUE THREAD

**Issue by iankityadav** [iankityadav/450dsa#4]
In VS code it is giving error for having Solution name for all the java files.
Need to change it to`Solution{Topic}{QuestionNumber}`

Refer Java Solution file of Q14 of Arrays

**Comment by tskarunasena** [comment]
I would like to contribute to this issue.

**Comment by iankityadav** [comment]
Pending in few topics listed below

- [ ] Bit Manipulation\1-Count Set Bits\Solution.java 
- [ ] Stacks and Queue\1-Implement Stack\Solution.java 
- [ ] String\1-Reverse a String\Solution.java 
- [ ] String\2-Palindrome String\Solution.java

**Comment by iankityadav** [comment]
completed in pr #12
